### ISSUE TITLE
Dumble Stacks?

### ISSUE THREAD

**Issue by 100amps** [jatalahd/tsc#1]
The Dumble stacks (Rock and Jazz) would be great additions to this.  They're different enough to not be able to model them here.

For more info, see this link... [https://ampgarage.com/forum/viewtopic.php?t=12175](https://ampgarage.com/forum/viewtopic.php?t=12175)

**Comment by jatalahd** [comment]
Thank you for suggesting the Dumble stacks. Now the Dumble rock and jazz stacks are added as given in the provided link. I did not verify what the pot types were for each control, but if necessary, pot types can be changed from the dropdown menu for each control.

The Dumble rock stack can be simplified from the crate stack by setting R3 = 0, C4 = 0 and R2 = 10 Meg. But still I decided to add the rock stack separately.

**Comment by 100amps** [comment]
Wow. Very cool. Well done. Thanks!

..Todd

**Comment by 100amps** [comment]
With apologies, I think I must have led you astray with that link. I’m no
Dumble expert, but the values and even the topology you’ve drawn is
somewhat different than the 4 commonly available schematics of different
Dumble ODS serial #s I’ve seen kicking around the web.

Maybe Merlin’s examples were from a different model amp than an Overdrive
Special.

I’ve attached a screenshot showing the most consistently used stack and
values in the available Dumble ODS schematics. 4 of the 5 amps I’m aware of
use this configuration. The amp that didn’t match was apparently later
updated to match, as I understand things.

**Comment by jatalahd** [comment]
I could not find any screenshot attachments. Please try again or send a new link to the correct schematic.

**Comment by 100amps** [comment]
![screenshot_20190217-235531 2](https://user-images.githubusercontent.com/18044808/52936743-fd618c80-3311-11e9-9e80-d21cb96fb359.png)

**Comment by jatalahd** [comment]
New versions of Dumble Rock and Jazz updated. The old models still exist, but they are no longer selectable from the top menu bar. The midboost switch in the new models can be simulated by increasing the value of C5 in my model to 100000000, for example.
