### ISSUE TITLE
Framus Mid Tone Control

### ISSUE THREAD

**Issue by themeadery** [jatalahd/tsc#2]
I am currently designing my own amp and I put a Framus mid tone control in it from Rob Robinette's site. I was hoping to see it in your stand alone app, then I stumbled on this web version and still no luck. Feature request? Taken from here: [https://robrobinette.com/Generic_Tube_Amp_Mods.htm#Framus_Mid_Control](url)

I use LTspice, but simulations take forever to run after a component tweak, including stepping parameters. Therefore your software is very useful because it is real-time. You tweak the knob and you see the results. Very cool.

**Comment by jatalahd** [comment]
Framus mid tone control added to TSC in the web. Please take a look at it in http://www.guitarscience.net/tsc/framus.htm . Is that what you requested for? Note that RIN affects the total response, so you need to change that to what is the output resistance of the previous stage before this tone control. In the actual Framus amp, it seems to be quite high, approx 100k, but I left the default value for RIN quite small.

I did not have time to test this against a SPICE model, I will do that in the coming weekend and if there are some errors in my simulation, I will fix those then. Also, if you notice something to fix, please let me know.

**Comment by themeadery** [comment]
That looks great! Thank you!

When you ask about output resistance, are you meaning output impedance of the tube? In my particular design, the output impedance is 60k right before the mid control. But my design is not very typical. With a 12AX7 it would typically be 68k (unbypassed cathode) to 38k (bypassed cathode).

If you are specifying just resistance, well, interestingly Rob Robinette recommends putting this mid control right after a volume pot. So, playing with your simulation more, I noticed if I put a volume pot in front of the mid control it does affect the high frequencies drastically if you have the volume pot, for example, up half way (Audio Logarithmic) and the resistance is 900K, the highs roll off drastically. This makes me want to experiment with the volume pot after the mid control! Somehow I didn't see that in my Spice simulation, which is why I am glad you added this to your software!

**Comment by jatalahd** [comment]
Yes I meant the output impedance of the tube, which reflects to RIN in the simulation model.

Tested against SPICE model, the results were the same. I updated an enhanced picture for the schematic (Vout was missing). Closing this issue.
