### ISSUE TITLE
Potentiometer model and source code comment

### ISSUE THREAD

**Issue by danieljfarrell** [jatalahd/tsc#5]
I remember using Duncan's TSC back in the early 2000s, it's great to see this on the web.

I'm curious about the comment on your info. page that says "potentiometer implementations (LogA and LogB) have been copied directly from the original TSC source code". Is the original TSC open-source? I would be really interested to read it to see how it has been put together and works. And also, know about how the pot. model work.

**Comment by jatalahd** [comment]
From the bottom of this page: https://www.duncanamps.com/tsc/linux.html

Download tonestack-2.0.1.src.tar.gz and enjoy ;) The pot models are in Units/uSymbol.pas 

I don't know the story behind the pot models, but they seem to be a simple linearisation model for the assumed pot resistance curve. The idea with this project was to replicate the original, so I took them and used them as is.

**Comment by danieljfarrell** [comment]
Thanks! When I first used TSC I didn’t even know to code!
