### ISSUE TITLE
Add a basic 'Tilt' filter (active)?

### ISSUE THREAD

**Issue by prosper00** [jatalahd/tsc#6]
Do you have any desire to add a basic tilt (hi/lo) filter? I find it to be a very useful filter for cases where a fairly straightforward single-pot filter is sufficient.

See 
http://vulcanofx.blogspot.com/p/tilt-eq-calculator.html

and

https://www.edn.com/implement-an-audio-frequency-tilt-equalizer-filter/

**Comment by jatalahd** [comment]
Done.
